- # 什么是协程
	- 协程，英文Coroutines，是一种比线程更加轻量级的存在。
	- 协程不是进程，也不是线程，它就是一个可以在某个地方挂起的特殊函数，并且可以重新在挂起处继续运行。
- # kotlin协程
  collapsed:: true
	- 经过上边的介绍我们大概了解到，协程只是一个概念，它并不是属于某个语言的特性。甚至同一语言在不同的平台上协程的实现也不一样。
	- 本文这里只讨论kotlin协程，他是一种“无栈协程”。至于为什么叫无栈协程我们后续在说。后文中所说的协程都默认kotlin协程。
- # 协程要干什么
  collapsed:: true
	- 个人理解协程其实就是和rxjava一样，主要是为了解决“回调地狱”的问题，使我们代码更优雅一些。至于线程切换我认为只是一种能力和方便
- # 协程的原理
  collapsed:: true
	- 本文只针对kotlin无栈协程做分析，如果你还没有这方面的经验可以先研究研究相关方面的基础。
	- 我们知道，启动协程的时候避免不了两个东西。一个是suspend函数，一个是Scope启动器launch、async 和 runBlocking。我们先一个例子开始来分析这两部分。
		- ```
		  class DemoByte {
		      fun main2()= runBlocking {
		          GlobalScope.launch {
		              doWorld()
		              doCity()
		          }
		          println("Hello,") // 主协程在这里会立即执行
		      }
		      private suspend fun doWorld(){
		          println("World!")
		      }
		  
		      private suspend fun doCity(){
		          println("City!")
		      }
		  
		  }
		  ```
- # suspend关键字
  collapsed:: true
	- 首先我们知道suspend函数可以调用正常函数，也可以嵌套suspend函数调用。但是反过来正常函数是不能直接调用suspend函数的。那这个suspend关键字究竟做了呢？
	- 我们可以拿studio提供的“照妖镜”来看看这个suspend函数。点击Tools->Kotlin->Show Kotlin Bytecode。查看kotlin编译后的字节码。
	  collapsed:: true
		- ```
		  // signature (Lkotlin/coroutines/Continuation<-Lkotlin/Unit;>;)Ljava/lang/Object;
		    // declaration:  doWorld(kotlin.coroutines.Continuation<? super kotlin.Unit>)
		    private final doWorld(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
		  ```
	- 可以清楚的看到doWorld函数的方法经过kotlin编译器变形后签名变成了带Continuation参数返回值为Object的函数。
	- 所以我们就很明确了，为什么正常函数不能调用suspend函数，因为正常函数没有Continuation这个参数。
	-
- # Continuation
  collapsed:: true
	- 那么Continuation这个又是个什么鬼东西。我们可以去翻阅下它的定义。
	  collapsed:: true
		- ```
		  public interface Continuation<in T> {
		      /**
		       * The context of the coroutine that corresponds to this continuation.
		       */
		      public val context: CoroutineContext
		  
		      /**
		       * Resumes the execution of the corresponding coroutine passing a successful or failed [result] as the
		       * return value of the last suspension point.
		       */
		      public fun resumeWith(result: Result<T>)
		      
		      @SinceKotlin("1.3")
		      @InlineOnly
		      public inline fun <T> Continuation<T>.resume(value: T): Unit =
		          resumeWith(Result.success(value))
		  
		      /**
		       * Resumes the execution of the corresponding coroutine so that the [exception] is re-thrown right after the
		       * last suspension point.
		       */
		      @SinceKotlin("1.3")
		      @InlineOnly
		      public inline fun <T> Continuation<T>.resumeWithException(exception: Throwable): Unit =
		          resumeWith(Result.failure(exception))
		  
		  }
		  
		  ```
	- 可以看到他是一个接口类，有一个关键的函数定义resumeWith。它的函数注释也写的很清楚，用一个失败或者成功结果作为返回值从挂起点恢复协程。
	- 所以我们可以这样理解。当协程走进suspend函数的时候，这个suspend函数又怎么回到原来调用他的函数里呢？靠的就是这个玩意。
	- 那这玩意到底又怎么回到挂起点的呢？这时候我们就需要看下他的实现类ContinuationImpl。
	  collapsed:: true
		- ```
		  // State machines for named suspend functions extend from this class
		  internal abstract class ContinuationImpl(
		      completion: Continuation<Any?>?,
		      private val _context: CoroutineContext?
		  ) : BaseContinuationImpl(completion) {
		      constructor(completion: Continuation<Any?>?) : this(completion, completion?.context)
		  
		      public override val context: CoroutineContext
		          get() = _context!!
		  
		      @Transient
		      private var intercepted: Continuation<Any?>? = null
		  
		      public fun intercepted(): Continuation<Any?> =
		          intercepted
		              ?: (context[ContinuationInterceptor]?.interceptContinuation(this) ?: this)
		                  .also { intercepted = it }
		  
		      protected override fun releaseIntercepted() {
		          val intercepted = intercepted
		          if (intercepted != null && intercepted !== this) {
		              context[ContinuationInterceptor]!!.releaseInterceptedContinuation(intercepted)
		          }
		          this.intercepted = CompletedContinuation // just in case
		      }
		  }
		  ```
	- 这里没有resumeWith的相关处理，我们需要看它的父类BaseContinuationImpl。在瞅他的父类之前我们先瞅下ContinuationImpl这个类。
	- 首先这有个注释‘State machines for named restricted suspend functions extend from this class’，状态机为命名的受限的挂起函数从这个类继承。
	- 这里学到了一个新概念“State machines”，那么什么是状态机呢？我们可以狭义的暂时理解就是Coroutine这个类。我们也可以延伸下就是就是控制整个协程挂起恢复的逻辑块，包括我们后边提到的switch代码块。
	- 在这里我们还看到intercepted()和releaseIntercepted()这两个关于协程拦截器的方法。对没错kotlin协程也有拦截器。但是本文就不对这个做具体分析了有兴趣的同学可以自己研究。
	- 我们接着回到BaseContinuationImpl这个类上来。
	  collapsed:: true
		- ```
		  internal abstract class BaseContinuationImpl(
		      // This is `public val` so that it is private on JVM and cannot be modified by untrusted code, yet
		      // it has a public getter (since even untrusted code is allowed to inspect its call stack).
		      public val completion: Continuation<Any?>?
		  ) : Continuation<Any?>, CoroutineStackFrame, Serializable {
		      // This implementation is final. This fact is used to unroll resumeWith recursion.
		      public final override fun resumeWith(result: Result<Any?>) {
		          // This loop unrolls recursion in current.resumeWith(param) to make saner and shorter stack traces on resume
		          var current = this
		          var param = result
		          while (true) {
		              // Invoke "resume" debug probe on every resumed continuation, so that a debugging library infrastructure
		              // can precisely track what part of suspended callstack was already resumed
		              probeCoroutineResumed(current)
		              with(current) {
		                  val completion = completion!! // fail fast when trying to resume continuation without completion
		                  val outcome: Result<Any?> =
		                      try {
		                          val outcome = invokeSuspend(param)
		                          if (outcome === COROUTINE_SUSPENDED) return
		                          Result.success(outcome)
		                      } catch (exception: Throwable) {
		                          Result.failure(exception)
		                      }
		                  releaseIntercepted() // this state machine instance is terminating
		                  if (completion is BaseContinuationImpl) {
		                      // unrolling recursion via loop
		                      current = completion
		                      param = outcome
		                  } else {
		                      // top-level completion reached -- invoke and return
		                      completion.resumeWith(outcome)
		                      return
		                  }
		              }
		          }
		      }
		  
		      protected abstract fun invokeSuspend(result: Result<Any?>): Any?
		  
		  }
		  ```
	- 首先可以看到resumeWith方法里有个while (true)死循环。这个死循环干啥的上边有个注释写的很清楚。‘This loop unrolls recursion in current.resumeWith(param) to make saner and shorter stack traces on resume’这个循环是为了确保协程已经进入了可resum状态。那啥时候resume？不知道我们接着往后看。
	  collapsed:: true
		- ```
		  val outcome: Result<Any?> =
		                      try {
		                          val outcome = invokeSuspend(param)
		                          if (outcome === COROUTINE_SUSPENDED) return
		                          Result.success(outcome)
		                      } catch (exception: Throwable) {
		                          Result.failure(exception)
		                      }
		  ```
	- 这个就很明白了，调用invokeSuspend方法，如果是‘COROUTINE_SUSPENDED’挂起状态呢那就跳出这个方法等待下次被调用。
	- 如果当前不是挂起状态呢，那就把结果包装到Result.success()的参数里继续往后走。
	- 在后边如果传来的Continuation是BaseContinuationImpl，那么就赋值下等待下次while(true)循环。否则就是顶层最后一个‘completion’，那么就调用completion.resumeWith(outcome)返回。
	- 这里可以看到这个while(true)不仅仅是校验invokeSuspend结果是不是非挂起状态。他还负责跟递归一样一层一层的调用每个Continuation的invokeSuspend直到调用到了最顶层的。
	- so，你彻底明白为啥suspend函数要有个Continuation参数并且它是干什么的了吗？
	- 你是不是就很好奇这个invokeSuspend到底是啥的？这时候我们别着急接着往后跟踪kotlin实现了，因为kotlin屏蔽了真正实现（反正我是感觉找到的实现怪怪的）。我们祭出究极大法直接看java实现。
	- 还是我们demo代码，然后点击Tools->Kotlin->Show Kotlin Bytecode，然后再点击Decompile。
	  collapsed:: true
		- ```
		  public final class DemoByte {
		     public final void main2() {
		        BuildersKt.runBlocking$default((CoroutineContext)null, (Function2)(new Function2((Continuation)null) {
		           int label;
		  
		           @Nullable
		           public final Object invokeSuspend(@NotNull Object var1) {
		              Object var3 = IntrinsicsKt.getCOROUTINE_SUSPENDED();
		              switch(this.label) {
		              case 0:
		                 ResultKt.throwOnFailure(var1);
		                 BuildersKt.launch$default((CoroutineScope)GlobalScope.INSTANCE, (CoroutineContext)null, (CoroutineStart)null, (Function2)(new Function2((Continuation)null) {
		                    int label;
		  
		                    @Nullable
		                    public final Object invokeSuspend(@NotNull Object $result) {
		                       Object var2 = IntrinsicsKt.getCOROUTINE_SUSPENDED();
		                       DemoByte var10000;
		                       switch(this.label) {
		                       case 0:
		                          ResultKt.throwOnFailure($result);
		                          var10000 = DemoByte.this;
		                          this.label = 1;
		                          if (var10000.doWorld(this) == var2) {
		                             return var2;
		                          }
		                          break;
		                       case 1:
		                          ResultKt.throwOnFailure($result);
		                          break;
		                       case 2:
		                          ResultKt.throwOnFailure($result);
		                          return Unit.INSTANCE;
		                       default:
		                          throw new IllegalStateException("call to 'resume' before 'invoke' with coroutine");
		                       }
		  
		                       var10000 = DemoByte.this;
		                       this.label = 2;
		                       if (var10000.doCity(this) == var2) {
		                          return var2;
		                       } else {
		                          return Unit.INSTANCE;
		                       }
		                    }
		  
		                    @NotNull
		                    public final Continuation create(@Nullable Object value, @NotNull Continuation completion) {
		                       Intrinsics.checkNotNullParameter(completion, "completion");
		                       Function2 var3 = new <anonymous constructor>(completion);
		                       return var3;
		                    }
		  
		                    public final Object invoke(Object var1, Object var2) {
		                       return ((<undefinedtype>)this.create(var1, (Continuation)var2)).invokeSuspend(Unit.INSTANCE);
		                    }
		                 }), 3, (Object)null);
		                 String var2 = "Hello,";
		                 System.out.println(var2);
		                 return Unit.INSTANCE;
		              default:
		                 throw new IllegalStateException("call to 'resume' before 'invoke' with coroutine");
		              }
		           }
		  
		           @NotNull
		           public final Continuation create(@Nullable Object value, @NotNull Continuation completion) {
		              Intrinsics.checkNotNullParameter(completion, "completion");
		              Function2 var3 = new <anonymous constructor>(completion);
		              return var3;
		           }
		  
		           public final Object invoke(Object var1, Object var2) {
		              return ((<undefinedtype>)this.create(var1, (Continuation)var2)).invokeSuspend(Unit.INSTANCE);
		           }
		        }), 1, (Object)null);
		     }
		  
		     private final Object doWorld(Continuation $completion) {
		        String var2 = "World!";
		        System.out.println(var2);
		        return Unit.INSTANCE;
		     }
		  
		     private final Object doCity(Continuation $completion) {
		        String var2 = "City!";
		        System.out.println(var2);
		        return Unit.INSTANCE;
		     }
		  }
		  
		  ```
	- 大家只用关心invokeSuspend方法就行。这时候看到这个这个switch和label是不是顿时就明白了。我们的suspend函数已经被转换成了switch代码块的一个case分支。我们刚才看到while(true)循环其实就是在一层一层的调用这个switch分支，即我们最直观的suspend方法。每一个suspend函数执行完了那就返回Unit.INSTANCE状态。直至最后一个完成后调用resumeWith方法恢复协程。所谓的挂起状态就是代码还在执行switch的case语句中。
	- 思考个问题如果中间某个协程出现异常崩溃了会如何？
- # 协程的本质
	-