- # 示例
  collapsed:: true
	- 代码
		- ```kotlin
		      fun launch2() {
		          GlobalScope.launch(Dispatchers.Main) {
		              println("我在主线程执行")
		              withContext(Dispatchers.IO) {
		                  println("我在子线程执行")//②
		              }
		              println("我在哪个线程执行？")//③
		          }
		      }
		  ```
	- ![image.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c91a3909e2394418bc2360e102ee2ab5~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp)
	- 分为父协程体红色   和 子协程体绿色
	- 当② 执行完成后，会切换到父协程执行，我们看看切换父协程的流程。
- ## 子协程恢复 都会调用到resumeWith函数
  collapsed:: true
	- ```kotlin
	  #BaseContinuationImpl.kt
	  override fun resumeWith(result: Result<Any?>) {
	      //...
	      while (true) {
	          //..
	          with(current) {
	              val completion = completion!! // fail fast when trying to resume continuation without completion
	              val outcome: Result<Any?> =
	                  try {
	                      //执行协程体
	                      val outcome = invokeSuspend(param)
	                      if (outcome === kotlin.coroutines.intrinsics.COROUTINE_SUSPENDED) return
	                      kotlin.Result.success(outcome)
	                  } catch (exception: Throwable) {
	                      kotlin.Result.failure(exception)
	                  }
	              releaseIntercepted() // this state machine instance is terminating
	              if (completion is BaseContinuationImpl) {
	                  //...
	              } else {
	                  //如果上一步的协程体不阻塞，则执行completion
	                  completion.resumeWith(outcome)
	                  return
	              }
	          }
	      }
	  }
	  ```
	- 恢复最终肯定调用的completion.resumeWith(outcome)方法。
	- 根据之前完整流程 launch方法创建的为StandaloneCoroutine
		- 父协程的Continuation的 completion = StandaloneCoroutine
- ## 如果子协程是withContex启动的，它的completion是谁？
  collapsed:: true
	- 根据[[WithContext挂起原理解析]]可知withContext的 completion为DispatchedCoroutine，传入的uCount 实参即为父协程的协程体即Continuation
	- 则withContext的 completion = DispatchedCoroutine ，DispatchedCoroutine 的 uCont = Continuation
- ## 此时，子协程体与父协程 通过DispatchedCoroutine 关联起来了。
  collapsed:: true
	- 当走到
		- ```kotlin
		  else {
		    // top-level completion reached -- invoke and return
		    completion.resumeWith(outcome)
		    return
		  }
		  ```
	- 如果是Launch函数 会走StandaloneCoroutine里的resumeWith
	- 但是这是withContex 会走DispatchedCoroutine的resumeWith
- ## DispatchedCoroutine的resumeWith
  collapsed:: true
	- ```kotlin
	  #AbstractCoroutine.kt
	      public final override fun resumeWith(result: Result<T>) {
	          val state = makeCompletingOnce(result.toState())
	          if (state === COMPLETING_WAITING_CHILDREN) return
	          afterResume(state)
	      }
	  
	  #Builders.common.kt
	  #DispatchedCoroutine 类里
	      override fun afterResume(state: Any?) {
	          //uCont 为父协程体
	          uCont.intercepted().resumeCancellableWith(recoverResult(state, uCont))
	      }
	  ```
- ## 可以看到 调用的是uCont.intercepted().resumeCancellableWith(recoverResult(state, uCont))
- 调用的父协程的拦截器，进行分发执行后续代码。由此转换完成了
- 到此就豁然开朗了，uCont.intercepted() 找到它的拦截器，因为uCont为MyAnnoy1，它的拦截器就是HandlerContext，又来了一次抛回到主线程执行。